volumes:
  bash-history:
  hex-files:
  mix-files:
  pg-data:

services:
  dev:
    build: .
    image: jps_app
    user: phantom
    volumes:
      - .:/home/phantom/app
      - bash-history:/home/phantom/bash-history
      - hex-files:/home/phantom/.hex
      - mix-files:/home/phantom/.mix
    environment:
      - SERVICE_NAME=JPS
    links:
      - db

  db:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/home/phantom/app
      - pg-data:/var/lib/postgresql/data/
